services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD:-StrongPassword123!}
    ports:
      - "${MSSQL_PORT:-1433}:1433"
    restart: always
    container_name: sqlserver
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app_network
    env_file:
      - .env

networks:
  app_network:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local
